### ISSUE TITLE
Multiple selections stay highlighted

### ISSUE THREAD

**Issue by cameronjj** [naturenet/naturenet-www#18]
If I click on the projects, design idea, or communities page, and then click back on the explore page, both the explore and prior pages nav elements are highlighted.

![screen shot 2016-08-21 at 12 18 57 pm](https://cloud.githubusercontent.com/assets/4220521/17839039/d037c1ac-6799-11e6-840c-2c2a092248ec.png)

**Comment by WildWeazel** [comment]
This is obviously not intuitive since people keep bringing it up. The explore view is actually an overlay not a page, so that you can access it from anywhere without losing whatever context you were in. But as a full page UI that is not an obvious distinction. If it's always going to take up the whole page we might as well make it a page (upcoming URL/state changes will make it easier to navigate back and forth and/or link to specific content, so that's irrelevant) or maybe it could be an expandable view that pops up in a corner when you select an observation from another page.

**Comment by WildWeazel** [comment]
tangentially related to #25

**Comment by stevemacn** [comment]
Fixed - it is no longer an overlay but its own page.
